# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

has_inter <- function(interaction, data, isFactor) {
    .Call('covRIT_has_inter', PACKAGE = 'covRIT', interaction, data, isFactor)
}

cpp_cov_RIT <- function(datas, theta, factor, epsilon_cont, epsilon_cat, spans, n_trees, depth, branch, split_nb, min_inter_sz, es) {
    .Call('covRIT_cpp_cov_RIT', PACKAGE = 'covRIT', datas, theta, factor, epsilon_cont, epsilon_cat, spans, n_trees, depth, branch, split_nb, min_inter_sz, es)
}

